ARG NSO_IMAGE_PATH
ARG NSO_VERSION

# DEP_START
# DEP_END


# Compile local packages in the build stage
FROM ${NSO_IMAGE_PATH}cisco-nso-dev:${NSO_VERSION} AS build
ARG PKG_FILE

COPY / /src
RUN for PKG in $(find /src/packages -mindepth 1 -maxdepth 1 -type d); do make -C ${PKG}/src || exit 1; make -f /src/nid/bmd.mk -C ${PKG} build-meta-data.xml; done


# produce the main NSO image that comes loaded with all our built both locally
# and included from external repositories
FROM ${NSO_IMAGE_PATH}cisco-nso-base:${NSO_VERSION} AS nso

# DEP_INC_START
# DEP_INC_END

# Copy in extra files as an overlay, for example additions to
# /etc/ncs/pre-ncs-start.d/
COPY extra-files /

COPY --from=build /packages/ /var/opt/ncs/packages/
