include nidvars.mk

# The default testenv should be a "quick" testenv, containing a simple test that
# is quick to run.
DEFAULT_TESTENV?=quick

# Include standard NID (NSO in Docker) system Makefile that defines all standard
# make targets
include nidsystem.mk
