* NSO in Docker for development and production
  This repository contains all you need to build Docker images out of Cisco NSO. It produces two Docker images;
  - a production image
    - stripped of documentation and similar to make it small
    - ... what else?
  - a development image
    - contains Java compiler and other useful tools
    - ... what else?

  The development image can be used immediately, for example as the image for a CI docker container runner to use for running CI jobs that involve compilation of NSO packages and similar. The production image is intended to be used as a base image on which you add your own packages, like NEDs and your service packages, to produce a final image for your environment.
   
* Usage
  
** Manually building Docker images locally
  - Clone this repository to your local machine
    - ~git clone git@github.com/NSO-Developer/cisco-nso.git~
  - Download Cisco NSO
    - TODO fill in URL
  - Place downloaded .bin file in ~nso-install-files/~
  - run ~make build~ in repository root directory
  - verify your new images are built with ~docker images~ which should look something like:

  #+BEGIN_SRC shell
    kll@ThinkLite:~/cisco-nso# docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    cisco-nso           5.2                 c451b581d328        19 hours ago        435MB
    cisco-nso           4.7.5               3096fe46bee9        19 hours ago        433MB
    cisco-nso-dev       5.2                 a986314ec390        22 hours ago        435MB
    <none>              <none>              7e680e680923        22 hours ago        410MB
    cisco-nso-dev       4.7.5               0565a58c3977        22 hours ago        433MB
    <none>              <none>              d968a53420ab        22 hours ago        421MB
    bitnami/minideb     buster              25dfa3b9a987        23 hours ago        67.5MB
    docker              stable              b40e5afd78f5        2 weeks ago         216MB
    kll@ThinkLite:~/cisco-nso#
  #+END_SRC

** Automatically building Docker images using Gitlab CI
  - Clone this repository to your local machine
    - ~git clone git@github.com/NSO-Developer/cisco-nso.git~
  - Download Cisco NSO
    - TODO fill in URL
  - Place downloaded .bin file in ~nso-install-files/~
  - commit file(s) in ~nso-install-files/~ using git LFS and push
    - ~git add nso-install-files/*~
    - ~git commit nso-install-files -m "Add NSO install files"~
      - it is a good practice to add the files one by one and write the version you added in the commit message, like "Add NSO install file for v4.7.5"
    - ~git push -u origin master~
    - CI will now build the docker images for you
      - naturally provided you first setup CI
  - verify your new images are built by going to the container repository in Gitlab viewing the list of container images

** Docker image tags
It is recommended that the Docker images are tagged with an identifier that is unique per build.
