
# TODO: rip this apart
# TODO: version-gen should take an argument for the file to create and based on what input
build-all4.yaml build-all5.yaml build-all.yaml build-tot4.yaml build-tot5.yaml build-tot.yaml multiver.yaml push-all4.yaml push-all5.yaml push-all.yaml push-tot4.yaml push-tot5.yaml push-tot.yaml versions.txt:
	../version-gen


generate: build-all4.yaml build-all5.yaml build-all.yaml build-tot4.yaml build-tot5.yaml build-tot.yaml multiver.yaml push-all4.yaml push-all5.yaml push-all.yaml push-tot4.yaml push-tot5.yaml push-tot.yaml versions.txt
